name: Hub Progression Rewards

on:
  schedule:
    - cron: "30 14 * * *"  # 8:00 PM IST
    - cron: "0 15 * * *"   # 8:30 PM IST
    - cron: "30 15 * * *"  # 9:00 PM IST
    - cron: "0 16 * * *"   # 9:30 PM IST
  workflow_dispatch:

jobs:
  run-progression-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Progression Script
        run: python g_hub_ProgressionProgram_rewards_updated.py

      - name: Send Email with Log
        run: python send_email_with_log.py
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
